project:
  type: website
  output-dir: docs

website:
  title: "Haylee Oyler"
  # favicon: images/my-favicon.png, adds logo to website bar thingy
  navbar:
    background: $uclablue
    foreground: $whiteblue
    highlight: $navyblue
    # title: true
    # logo: images/my-logo.png, adds logo to navbar 
    # logo-alt: "my alt text"
    right:
      - href: about.qmd
        text: About
      - posts.qmd
      - href: photos.qmd
        text: Photos
      - href: resources.qmd
        text: Resources
      - text: CV
        href: resumes/hoyler-cv.pdf
        target: _blank # Make resume open in new page
  page-footer: 
    border: false
    foreground: $navyblue
    background: transparent
    left: "&copy; 2024 Haylee Oyler"
    right: 
      - href: mailto:hoyler@bren.ucsb.edu
        icon: envelope
      - href: https://www.linkedin.com/in/haylee-oyler-788b7619a/
        icon: linkedin
        target: _blank
      - href: https://github.com/haylee360/haylee360.github.io
        target: _blank
        icon: github
        aria-label: GitHub

    # right: This website is build with GitHub {{< fa brands github title="octocat github icon" >}}

format:
  html:
    theme: styles/styles.scss
    mainfont: Figtree
    # css: styles.css, not using a css file, can even delete from repo
    toc: false
    page-layout: full
    page-footer:
      fontsize: 14px

